version: '3.3'

# this is a SAMPLE file. Do not use for build or deployments

# use the following to restrict which OS this is built on
# containerOS: alpine

services:
    smee:
        build:
# build arguements
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: smee
                FROM_BASE: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
                SMEE _USER: smee
            cache_from:
                - ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.build.time: $CONTAINER_BUILD_TIME
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.original.name: smee
                container.parent: $CONTAINER_PARENT
                version.cbf: $CBF_VERSION
        container_name: smee
# config parameters for smee (jenkins used for example)
        environment:
            SMEE_URL: https://smee.io/F9gFiEeTza0Po4Rd
            SMEE_PORT: 8080
            SMEE_PATH: /jenkins/github-webhook/
            SMEE_TARGET: http://localhost/
        hostname: smee
        image: ${DOCKER_REGISTRY:-ubuntu-s2:5000/}${CONTAINER_OS:-alpine}/smee:${CONTAINER_TAG:-latest}
# limit size of logs @runtime so that we do not run out of space
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        restart: unless-stopped               # only use when building a 'service container' 
